### PR TITLE
update metadata gogoduck link #328

### PR DESCRIPTION
**Pull request by bhasin85**

### CODE REVIEW

**Comment by jonescc** [comment]
Would like to merge this - but can't as its to julian's repo.

@julian1 - if this repo contains AODN source code we shouldn't be forking it from yours.

**Comment by jonescc** [comment]
@julian1 I'd also suggest changing the repository name - its not very descriptive.

**Comment by jonescc** [comment]
Changes look good to me.  @julian1 can you give emii developers permission to merge pull requests in this repository?

**Comment by julian1** [comment]
eMII Development Team now have write permissions. Could you try to merge again?

**Pull request merged**
